// src/cli/arguments.rs
pub const EXIT_EXTRACTING_ARGS_FAILED: i32 = 2;
pub const EXIT_KEYSIZE_ARG_IS_UNSIGNED_INT: i32 = 3;
pub const EXIT_THREAD_COUNT_ARG_IS_UNSIGNED_INT: i32 = 4;
pub const EXIT_BYTE_COUNT_ARG_IS_UNSIGNED_INT: i32 = 5;

pub const EXIT_READ_BYTES_TO_VECTOR_FAILED: i32 = 10;
pub const EXIT_READ_PART_BYTES_TO_VECTOR_FAILED: i32 = 11;

pub const EXIT_OUTPUT_FILE_NOT_WRITEABLE: i32 = 20;
pub const EXIT_EXISTING_OUTPUT_FILE_CANNOT_BE_REMOVED: i32 = 21;
