// arguments
pub const EXIT_EXTRACTING_ARGS_FAILED: i32 = 2;
pub const EXIT_KEYSIZE_ARG_IS_UNSIGNED_INT: i32 = 3;
pub const EXIT_THREAD_COUNT_ARG_IS_UNSIGNED_INT: i32 = 4;
pub const EXIT_BYTE_COUNT_ARG_IS_UNSIGNED_INT: i32 = 5;
pub const EXIT_ENTROPY_DELTA_ARG_IS_F32: i32 = 6;

// read_bytes
pub const EXIT_READ_BYTES_TO_VECTOR_FAILED: i32 = 10;

// write_ck
pub const EXIT_OUTPUT_FILE_CAN_NOT_BE_CREATED: i32 = 20;
pub const EXIT_OUTPUT_FILE_NOT_WRITEABLE: i32 = 21;
pub const EXIT_EXISTING_OUTPUT_FILE_CANNOT_BE_REMOVED: i32 = 22;
pub const EXIT_OUTPUT_FOLDER_CAN_NOT_BE_CREATED: i32 = 23;
